# -*- coding: utf-8 -*-
"""hw2-netflixPD.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GEp1MK-uznC4TO6wlIQ5JKiP6FsY4eak
"""

import numpy as np
import pandas as pd

netflix=pd.read_csv('/content/NetflixOriginals.csv',encoding = 'ISO-8859-1')

"""# IMDB puanı en yüksek olan ilk 10 film hangileridir?

"""

netflix.info()

top_10_movies = netflix[["IMDB Score", "Title", "Genre", "Premiere","Runtime", "Language"]].sort_values(["IMDB Score"], ascending=False)[:10]
top_10_movies

"""# Veri setine göre uzun soluklu filmler hangi dilde oluşturulmuştur? Görselleştirme yapınız.

"""

import seaborn as sns
import matplotlib.pyplot as plt

top_11_movies = netflix[["Language", "Title", "Genre", "Premiere","Runtime", "IMDB Score"]].sort_values(["Runtime"], ascending=False)
top_11_movies

netflix.Language.value_counts()

top_5_lang = netflix.Language.value_counts().nlargest(5)
top_5_lang

plt.figure(figsize=(20,8))
sns.barplot(x=top_5_lang.index, y=top_5_lang.values)
plt.title("Uzun soluklu filmlerin Dilleri")
plt.xticks(rotation=90)

"""# 2019 Ocak ile 2020 Haziran tarihleri arasında 'Documentary' türünde çekilmiş filmlerin IMDB değerlerini bulup görselleştiriniz."""

#df = netflix[(netflix['Premiere'] > 'January 1, 2019') & (netflix['Premiere'] <= 'June 31, 2020')]

netflix["Date"] = pd.to_datetime(netflix.Premiere)
netflix["Year"] = netflix["Date"].dt.year
netflix["Month"] = netflix["Date"].dt.month
netflix["day_of_week"] = netflix["Date"].dt.dayofweek
netflix["Year_Month"] = netflix["Date"].dt.strftime("%Y-%m")

netflix.head(10)

df = netflix[(netflix['Date'] > '2019-01-01') & (netflix['Date'] <= '2020-07-30')]

df

genre_doc=df[(df["Genre"] == "Documentary")]

genre_doc

fig =plt.figure(figsize = (18,5))

#Use the .add_subplot() method to add the line plot
first_plot = fig.add_subplot(1,3,1)
#Change the color to red
first_plot.scatter(genre_doc["IMDB Score"],genre_doc["Date"],label= "stars", color= "green", 
            marker= "*", s=30)
#Add the title
first_plot.set_title("2019 Ocak 2020 Haziran Arası Documentary Türünde çekilen filmlerin IMDB Puanları")

#plt.figure(figsize=(12,6))
#
#plt.plot(genre_doc["IMDB Score"] ,genre_doc.Date)
#
#plt.title("2019 Ocak 2020 Haziran Arası Documentary Türünde çekilen filmlerin IMDB Puanları")
#
#plt.show()

"""# İngilizce çekilen filmler içerisinde hangi tür en yüksek IMDB puanına sahiptir?"""

language_eng=df[(df["Language"] == "English")]
language_eng[["IMDB Score", "Title", "Genre", "Language"]].sort_values(["IMDB Score"], ascending=False).head(1)
#df[df["Language"] == "English"].sort_values(by="IMDB Score").tail(1)
#df[df["Language"] == "English"].sort_values(by="IMDB Score",ascending=False).head(1)